POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "domain": "electricity",
    "question": "hay una discrepancia en las lecturas"
}

###

POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "domain": "gas",
    "question": "holis"
}

###

POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "domain": "gas",
    "question": "opciones de gas"
}

###

POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "question": "Voy a quedar sin gas?"
}