POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "question": "holis"
}

###

POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "question": "opciones de gas"
}

###

POST http://localhost:3000/es/bot HTTP/1.1
Content-Type: application/json

{
    "question": "Voy a quedar sin gas?"
}